version: "3.7"

networks:
  external-pod:
    internal: false

services:
  python-bash:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app:delegated
    tty: true
    command:
      - "/bin/sh"
    networks:
      - external-pod
